version: '3.3'

services:
  data-ml-app:
    build:
      context: ./data/Modelo Machine
      dockerfile: Dockerfile
    container_name: data-ml-app
    ports:
      - "8000:8000"
    restart: always

  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      - MODELO_API_URL=http://data-ml-app:8000/predict
      - SPRING_PROFILES_ACTIVE=mysql-oci,mock
      - DB_HOST=10.0.0.140
      - DB_PORT=3306
      - DB_NAME=energiai
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - JAVA_TOOL_OPTIONS=-Xmx350m -Xms128m
    depends_on:
      - data-ml-app
    restart: always

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend-app
    restart: always