spring.application.name=backend
#spring.profiles.active=mock
spring.profiles.active=http
energiai.tarifa-referencia-kwh=0.75
spring.jackson.property-naming-strategy=SNAKE_CASE
springdoc.swagger-ui.path=/swagger
modelo.api.url=http://localhost:8000/predict
