# --- CONEXIÓN A HEATWAVE ---
spring.datasource.url=jdbc:mysql://${DB_HOST:10.0.0.140}:${DB_PORT:3306}/${DB_NAME:energiai}?useSSL=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.url=jdbc:mysql://${DB_HOST:10.0.0.140}:${DB_PORT:3306}/${DB_NAME:energiai}?useSSL=true
spring.flyway.user=${DB_USERNAME:admin}
spring.flyway.password=${DB_PASSWORD}
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true